"""bp_traj.py — extract a top bot's BOARD TRAJECTORY from its live replay
.  Ground truth = their actual states, not
re-simulated actions.

Per day: crop counts (h12), plants made (new planted_day), animals by
species, hands (h12), money, buys/hires from actions, sells by product
with hour buckets.  Emits (a) a human table, (b) --emit python literal
blueprint {day: {...}} for embedding.

Usage: python tools/bp_traj.py <replay.json> <SEAT_NAME> [--emit out.py]
"""
import json, sys
from collections import Counter, defaultdict

path, name = sys.argv[1], sys.argv[2]
emit = sys.argv[4] if len(sys.argv) > 4 and sys.argv[3] == "--emit" else None
blob = json.load(open(path, encoding="utf-8"))
names = blob["info"]["TeamNames"]
seat = names.index(name)
steps = blob["steps"]

BP = {}
prev_tiles = None
for d in range(30):
    t12 = min(d * 24 + 12, len(steps) - 1)
    o = steps[t12][seat]["observation"]
    farm = o["farms"][seat]
    crops = Counter()
    animals = Counter()
    parity = Counter()
    for row in farm["tiles"]:
        for x in row:
            if isinstance(x, dict):
                if x.get("crop"):
                    crops[x["crop"]] += 1
                    if x["crop"] == "STRAWBERRY":
                        parity[x.get("planted_day", 0) % 2] += 1
                if x.get("animal"):
                    animals[x["animal"]] += 1
    hands = len(farm.get("hands", []))
    money = farm["money"]
    # actions across the day
    plants = Counter(); buys = Counter(); hires = 0
    sells = Counter(); sell_hours = Counter()
    for h in range(24):
        t = d * 24 + h
        if t >= len(steps):
            break
        a = steps[t][seat].get("action") or {}
        if not isinstance(a, dict):
            continue
        for v in [a.get("farmer")] + list(a.get("hands") or []):
            if v and v[0] == "PLANT" and len(v) > 1:
                plants[v[1]] += 1
        for m in (a.get("market") or []):
            if not m:
                continue
            if m[0] == "HIRE":
                hires += 1
            elif m[0] in ("BUY_SEED", "BUY_ANIMAL", "BUY_PRODUCT") and len(m) > 2:
                try: buys[(m[0][4:], m[1])] += int(m[2])
                except Exception: pass
            elif m[0] == "SELL" and len(m) > 2:
                try:
                    sells[m[1]] += int(m[2]); sell_hours[h] += 1
                except Exception: pass
    BP[d] = dict(crops=dict(crops), animals=dict(animals), hands=hands,
                 money=int(money), plants=dict(plants), buys=dict(buys),
                 hires=hires, sells=dict(sells),
                 sell_hours=dict(sell_hours), str_parity=dict(parity))

print(f"{name} seat {seat}  final money {BP[29]['money']:,}")
print(f"{'d':>2} {'STR':>3}{'WHE':>4}{'MEL':>4}{'CAR':>4}{'TOM':>4} | "
      f"{'G':>2}{'C':>3}{'S':>3} {'hnd':>3} {'hire':>4} | plants | sells (u)")
for d in range(30):
    b = BP[d]; c = b["crops"]; a = b["animals"]
    pl = " ".join(f"{k[:3]}{v}" for k, v in sorted(b["plants"].items()))
    se = " ".join(f"{k[:3]}{v}" for k, v in sorted(b["sells"].items()) if v)
    print(f"{d:2d} {c.get('STRAWBERRY',0):3d}{c.get('WHEAT',0):4d}"
          f"{c.get('MELON',0):4d}{c.get('CARROT',0):4d}{c.get('TOMATO',0):4d} | "
          f"{a.get('GOOSE',0):2d}{a.get('COW',0):3d}{a.get('SHEEP',0):3d} "
          f"{b['hands']:3d} {b['hires']:4d} | {pl:<24s} | {se}")
if emit:
    with open(emit, "w", encoding="utf-8") as fh:
        fh.write("# AUTO-GENERATED by tools/bp_traj.py — board trajectory of "
                 f"{name} ({path}).  LOCAL data, our code.\n")
        fh.write("BLUEPRINT = " + repr(BP) + "\n")
    print(f"\nemitted -> {emit}")
